### ISSUE TITLE
TS and Cypress compatibility issues

### ISSUE THREAD

**Issue by jordandlaman** [palmerhq/cypress-image-snapshot#13]
Having difficulty getting this working with the typescript variant of cypress.  Also looks like the new version of cypress doesn't like you wrapping commands as the example errors out on run.  Main problem I am getting is that there are no type defs and cypress is saying the snapshotmatching commands are not chainable off the cy namespace.

**Comment by crosscompile** [comment]
Thanks for pointing out that issue!  I recently published some fixes but forgot to upgrade the dependencies in the example, just merged #14 to fix that.

I also use Cypress with TypeScript and need to get around to publishing some types for this package.  Until then I think adding the following declaration to `cypress/support/commands.ts` should work:
```ts
declare global {
  namespace Cypress {
    interface Chainable {
      matchImageSnapshot: (options? : any) => void;
    }
  }
}
```

**Comment by jordandlaman** [comment]
Thanks for the feedback!  I get ```Error: Cannot find module './commands' from '/Users/m54148/sites/cypriot/cypress/support'``` when running the spec.  Renaming cypress/support/index.js with the import './commands' to a .ts file pops the ts error that ```cy.matchImageSpanshot();``` is not chainable again.  Did you run into this before when globally declaring the namespace?

**Comment by crosscompile** [comment]
Interesting, I did have a couple of issues setting up TypeScript with Cypress that were resolved by a combination of `tsconfig.json` changes and declaring the namespace I shared.

That said our TypeScript environments could be different.  It might help to see if you can get any custom command working, something like:
```ts
declare global {
  namespace Cypress {
    interface Chainable {
      getTypeScriptWorking: typeof getTypeScriptWorking;
    }
  }
}

function getTypeScriptWorking() {
	console.log('It works!');
}

Cypress.Commands.add('getTypeScriptWorking', getTypeScriptWorking);
```

And then try adding `matchImageSnapshot` afterwards, that way you can pick apart the errors related to this package vs. general TypeScript with Cypress issues.

**Comment by jordandlaman** [comment]
Yeah so calling declare global TS doesn't like that.  I can run custom commands using 
```javascript   
// tslint:disable-next-line:no-namespace
declare namespace Cypress {
        // tslint:disable-next-line interface-name
        interface Chainable {
            foo: () => string
        }
}
```

But still doesn't fix trying to import in that file.

**Comment by jordandlaman** [comment]
I am gonna close this as this is potentially on cypress or my env.  Would be nice to have a milestone for type defs.

**Comment by jordandlaman** [comment]
Went with the jest option.  Works great.  Cheers!

**Comment by Keysox** [comment]
I went ahead and added typings for folks to use: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41222 

Now, all you need to do is `yarn add @types/cypress-image-snapshot -D` for this plugin to work with TypeScript!
